export default ACTIONS = {
    ACTION_GET_DAYS_BY_MONTH: 'ACTION_GET_DAYS_BY_MONTH',
    ACTION_GET_WEATHER: 'ACTION_GET_WEATHER',
    ACTION_GET_DETAIL: 'ACTION_GET_DETAIL',
    ACTION_GET_TODOLIST: 'ACTION_GET_TODOLIST',
}